# Generated by Django 3.2.16 on 2023-02-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_about_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name_plural': 'About Us'},
        ),
    ]
