# Generated by Django 3.2.16 on 2023-02-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_about_us_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_us',
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
    ]
