# Generated by Django 3.2.16 on 2023-02-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/events'),
        ),
    ]
