# Generated by Django 3.2.16 on 2023-02-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nos_entrées',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
