# Generated by Django 3.2.16 on 2023-02-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_nos_biriyani_nos_nans_nos_paratha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Café',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item_type', models.CharField(default='Café', max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='media/menu')),
            ],
        ),
        migrations.CreateModel(
            name='MENU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item_type', models.CharField(default='Menu', max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='media/menu')),
            ],
        ),
        migrations.CreateModel(
            name='Nos_Boisson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item_type', models.CharField(default='Boisson', max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='media/menu')),
            ],
        ),
        migrations.CreateModel(
            name='Nos_Chaudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item_type', models.CharField(default='Chaudes', max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='media/menu')),
            ],
        ),
        migrations.CreateModel(
            name='Nos_Cocktails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item_type', models.CharField(default='Cocktails', max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='media/menu')),
            ],
        ),
        migrations.CreateModel(
            name='Nos_Crustacés',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item_type', models.CharField(default='Crustacés', max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='media/menu')),
            ],
        ),
        migrations.CreateModel(
            name='Nos_desserts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item_type', models.CharField(default='desserts', max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='media/menu')),
            ],
        ),
        migrations.CreateModel(
            name='Nos_Frites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item_type', models.CharField(default='Frites', max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='media/menu')),
            ],
        ),
        migrations.CreateModel(
            name='Nos_Lassis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item_type', models.CharField(default='Lassis', max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='media/menu')),
            ],
        ),
        migrations.CreateModel(
            name='Nos_légumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item_type', models.CharField(default='légumes', max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='media/menu')),
            ],
        ),
        migrations.CreateModel(
            name='Nos_Plats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item_type', models.CharField(default='Plats', max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='media/menu')),
            ],
        ),
        migrations.CreateModel(
            name='Nos_Poulets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item_type', models.CharField(default='Poulets', max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='media/menu')),
            ],
        ),
        migrations.CreateModel(
            name='Nos_sauces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item_type', models.CharField(default='sauces', max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='media/menu')),
            ],
        ),
        migrations.CreateModel(
            name='Nos_Viandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item_type', models.CharField(default='Viandes', max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='media/menu')),
            ],
        ),
        migrations.AlterField(
            model_name='nos_biriyani',
            name='item_type',
            field=models.CharField(default='Biriyani', max_length=30),
        ),
        migrations.AlterField(
            model_name='nos_nans',
            name='item_type',
            field=models.CharField(default='Nans', max_length=30),
        ),
        migrations.AlterField(
            model_name='nos_paratha',
            name='item_type',
            field=models.CharField(default='Paratha', max_length=30),
        ),
    ]
